#!/bin/bash

CACHE_PATH=$1
if [ -z "$CACHE_PATH" ]; then
  echo "Usage: $0 path_to_cache"
  exit 1
fi

if [ ! -f cache_hashes.txt ]; then
  echo "You don't have cache_hashes.txt yet."
  exit 1
fi

hashdeep -v -a -k cache_hashes.txt -r -l $CACHE_PATH
