#!/bin/bash

CONTEXT=$1
if [ -z "$CONTEXT" ]; then
  echo "Usage: $0 build-context"
  exit 1
fi

if [ -z "$GCE_CACHE_BUCKET" ]; then
  echo "GCE cache bucket not set."
  exit 1
fi

echo "Downloading using build context ${CONTEXT}..."
if ! gsutil cp gs://${GCE_CACHE_BUCKET}/${CONTEXT}.tar.gz ./build-cache.tar.gz; then
  echo "Download failed, probably doesn't exist."
  exit 1
fi

echo "Download complete."
