#!/bin/bash
set -e
set +x
source ~/.nvm/nvm.sh
npm install @fusebot/jenkins-js-scripts
mv ./node_modules/@fusebot/jenkins-js-scripts ./jenkins_scripts
rm -rf ./node_modules
./jenkins_scripts/jenkins_setup_git.bash
