#!/bin/bash

CACHE_PATH=$1
if [ -z "$CACHE_PATH" ]; then
  echo "Usage: $0 path_to_cache"
  exit 1
fi

if ! [ "$(ls -A $CACHE_PATH)" ]; then
  touch $CACHE_PATH/.keep_dir
fi
hashdeep -l -r $CACHE_PATH > cache_hashes.txt
