#!/bin/bash

CONTEXT=$1
ARCHIVE=$2

if [ -z "$CONTEXT" ]; then
  echo "Usage: $0 build-context [archive]"
  exit 1
fi

if [ -z "$ARCHIVE" ]; then
  ARCHIVE=build-cache.tar.gz
fi

if [ -z "$GCE_CACHE_BUCKET" ]; then
  echo "GCE cache bucket not set."
  exit 1
fi

if [ ! -f $ARCHIVE ]; then
  echo "$ARCHIVE must exist."
  exit 1
fi

echo "Uploading using build context ${CONTEXT}..."
if ! gsutil cp $ARCHIVE gs://${GCE_CACHE_BUCKET}/${CONTEXT}.tar.gz ; then
  echo "Upload failed."
  exit 1
fi
